import type { Metadata } from "next";
import localFont from 'next/font/local';
import "./globals.css";

// 'IntroCaps-Gilroy', Arial, sans-serif;

const gilroy = localFont({
  src: [
    {
      path: '../../public/fonts/GilroyRegular.ttf',
     weight: '300',
      style: 'normal'
    },
      {
      path: '../../public/fonts/GilroyMedium.ttf',
     weight: '500',
      style: 'medium'
    },
     {
      path: '../../public/fonts/gilroy-extrabold.woff2',
     weight: '600',
      style: 'bold'
    }
  ],
  variable: '--font-gilroy', // CSS переменная
  display: 'swap', // Оптимизация загрузки
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${gilroy.variable}  `}
      >
        {children}
      </body>
    </html>
  );
}
